name: lms
description: Link Management System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sqflite_common_ffi: ^2.2.1+1
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  about: ^2.1.1
  package_info_plus: ^3.0.2
  adaptive_dialog: ^1.8.2
  launch_at_startup: ^0.2.1
  #auto_updater: ^0.1.6 NEED ADDITIONAL REQUIREMENT
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  msix: ^3.7.0

msix_config:
  display_name: LMS
  publisher_display_name: Francesco Vezzani
  identity_name: francesco.vezzani.lms
  msix_version: 0.0.2.3
  logo_path: ./asseets/icon.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - CHANGELOG.md
    - CONTRIBUTING.md