name: lms
description: Link Management System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  sqflite_common_ffi: ^2.1.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  about: ^2.1.1
  package_info_plus: ^1.4.2
  adaptive_dialog: ^1.5.0+1
  launch_at_startup: ^0.1.7
  auto_updater: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  msix: ^3.5.1

msix_config:
  display_name: LMS
  publisher_display_name: Francesco Vezzani
  identity_name: francesco.vezzani.lms
  msix_version: 0.0.1.2
  logo_path: ./asseets/icon.png

flutter:

  uses-material-design: true

  assets:
    - assets/