name: lms
description: Link Management System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basic
  url_launcher: ^6.1.10
  sqflite_common: ^2.4.2+2
  sqflite_common_ffi: ^2.2.1+1
  shared_preferences: ^2.0.18
  package_info_plus: ^3.0.3
  auto_updater: ^0.1.6

  # Design
  about: ^2.1.1
  cupertino_icons: ^1.0.5
  adaptive_dialog: ^1.8.2
  flutter_easyloading: ^3.0.5

  #launch_at_startup: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - CHANGELOG.md
    - CONTRIBUTING.md