name: lms
description: Link Management System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Using previous version to see if auto-update works on windows
version: 1.0.1+8 #Online macOS 1.0.1+9 windows 1.0.1+9

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basic
  url_launcher: ^6.1.11
  sqflite_common: ^2.4.5
  sqflite_common_ffi: ^2.2.5
  shared_preferences: ^2.1.1
  package_info_plus: ^4.0.1
  auto_updater: ^0.1.6

  # Design
  about: ^2.1.3
  cupertino_icons: ^1.0.5
  adaptive_dialog: ^1.8.3+1
  flutter_easyloading: ^3.0.5

  #launch_at_startup: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - CHANGELOG.md
    - CONTRIBUTING.md