app_id: 522E4865-600A-44EE-A635-B31EE4E25742
publisher: FrancescoVezzani
publisher_url: https://github.com/kekko7072/lms
display_name: LMS
create_desktop_icon: true
install_dir_name: LMS
script_template: custom_inno_script.iss
locales:
  - en